source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'active_model_serializers', '~> 0.10.4'
gem 'carrierwave'
gem 'devise'
gem 'grape'
gem 'grape_on_rails_routes'
gem 'grape-knock'
gem 'grape-route-helpers'
gem 'grape-swagger'
gem 'grape-swagger-rails'
gem 'grape-active_model_serializers'
gem 'interactor', '~> 3.0'
gem 'responders'
gem 'rest-client'
gem 'selenium-webdriver'
gem 'rails', '~> 6.1.3'
gem 'rack-cors'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'jsonapi-serializer'
gem 'jbuilder', '~> 2.7'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'launchy'

  gem 'bullet'
  gem 'capybara-email'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'json_spec'
  gem 'dotenv-rails'
  gem 'webdrivers', '~> 4.0'
end

group :development do
  gem 'better_errors'
  gem 'foreman'

  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'database_cleaner'
  gem 'simplecov', require: false
end
